services:

  mysql:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - bridge

  grafana:
    build:
      context: .
      dockerfile: ./docker/grafana/Dockerfile
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - bridge
    depends_on:
      - mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5
    restart: unless-stopped
    environment:
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PORT=${MYSQL_PORT}
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    networks:
      - bridge
    depends_on:
      - mysql

  meshtastic:
    build:
      context: .
      dockerfile: ./docker/meshtastic/Dockerfile
    container_name: meshtastic
    restart: unless-stopped
    privileged: true
    environment:
      - INTERFACE=${INTERFACE}
      - INTERFACE_PORT=${INTERFACE_PORT}
      - INTERFACE_HOST=${INTERFACE_HOST}
      - INTERFACE_ADDR=${INTERFACE_ADDR}

      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_TABLE=${MYSQL_TABLE}
    volumes:
      - ./:/app
    networks:
      - bridge
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

networks:
  bridge:
    driver: bridge

volumes:
  grafana_data:
  mysql_data: