FROM grafana/grafana-oss:11.2.7

COPY docker/grafana/provisioning/datasources/datasources.yaml /etc/grafana/provisioning/datasources/datasources.yaml
COPY docker/grafana/provisioning/dashboards/* /etc/grafana/provisioning/dashboards/*