{
 "title": "Mesh Overview",
 "description": "Overview of the local Meshtastic network",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Nodes",
    "label": "Nodes",
    "query": "SELECT CONCAT(long_name, \" \", \"(\", node_id, \")\") AS __text, node_id as __value\nFROM node_details \nORDER BY long_name ASC;"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total nodes in mesh",
   "type": "stat",
   "description": "Total number of observed nodes in the mesh",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT COUNT(node_id) \nFROM node_details \nWHERE node_id <> '0';"
    }
   ]
  },
  {
   "title": "Active nodes in the last 30 minutes",
   "type": "stat",
   "description": "Nodes that sent any packet in the last 30 minutes",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT COUNT(*) \nFROM node_details \nWHERE updated_at  >= NOW() - INTERVAL 30 MINUTE;"
    }
   ]
  },
  {
   "title": "Nodes naming status",
   "type": "stat",
   "description": "How many nodes are unknown and how many are known.\n\nThe unknown are ones that are either NULL in their long name or \"Unknown\" in their value",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(CASE WHEN long_name IS NULL OR long_name = 'Unknown' AND node_id != '0' THEN 1 END) AS \"Unnamed\",\n    COUNT(CASE WHEN long_name IS NOT NULL AND long_name != 'Unknown' AND node_id != '0' THEN 1 END) AS \"Named\"\nFROM\n    node_details\n\n"
    }
   ]
  },
  {
   "title": "Total packets sent",
   "type": "stat",
   "description": "Total packets sent in specified time range",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT COUNT(*) \nFROM mesh_packet_metrics \nWHERE source_id IN ($Nodes);\n"
    }
   ]
  },
  {
   "title": "Data sent on mesh in last hour",
   "type": "stat",
   "description": "Shows the total data sent on the mesh in bytes in the last hour. This includes all types of packets.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "meshtastic",
     "expr": "sum(sum_over_time(text_message_app_size_in_bytes{source_id=~\"$Nodes\"}[1h]))",
     "legendFormat": "__auto",
     "rawSql": "SELECT SUM(message_size_bytes)\nFROM mesh_packet_metrics \nWHERE rx_time >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 HOUR) AND source_id IN ($Nodes);"
    }
   ]
  },
  { "title": "Mesh Nodes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Nodes",
   "type": "table",
   "description": "List of Nodes",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  node_details.node_id AS \"Node ID\",\n  node_details.short_name AS \"Shortname\",\n  node_details.long_name AS \"Longname\",\n  node_details.hardware_model AS \"Hardware\",\n  device_metrics.battery_level AS \"Battery (%)\",\n  device_metrics.channel_utilization AS \"ChanUtil (%)\",\n  device_metrics.air_util_tx AS \"AirUtilTX (%)\"\nFROM node_details \nJOIN device_metrics ON node_details.node_id = device_metrics.node_id\nWHERE node_details.node_id <> '0' AND node_details.node_id IN($Nodes)\nORDER BY node_details.node_id;"
    }
   ]
  },
  { "title": "General Nodes Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Duty Cycle (AirUtilTX)",
   "type": "timeseries",
   "description": "This panel shows the percentage of airtime used for transmissions in the last hour. Airtime in LoRa networks represents the duration a device occupies the radio frequency channel to send data. It's a critical metric for:\n\nNetwork capacity: Higher airtime usage indicates increased network load.\n\nRegulatory compliance: Many regions limit the total airtime per device.\n\nBattery life: More airtime generally means higher power consumption.\n\nThe data comes from Meshtastic packets, reflecting actual network usage. High percentages may suggest the need for optimization or capacity planning.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "telemetry_app_air_util_tx{node_id=~\"$Nodes\"} > -100\nand\ndelta(telemetry_app_air_util_tx{node_id=~\"$Nodes\"}[1m]) != 0",
     "legendFormat": "{{long_name}}",
     "rawSql": "SELECT \n    nd.long_name,\n    dm.air_util_tx AS \"AirUtilTX\",\n    dm.time\nFROM device_metrics AS dm \nJOIN node_details AS nd ON dm.node_id = nd.node_id\nWHERE dm.node_id IN ($Nodes)\n  AND dm.air_util_tx IS NOT NULL\n  AND dm.air_util_tx > -100\nORDER BY dm.time;"
    }
   ]
  }
 ]
}