{
 "title": "Main Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Nodes",
    "label": "Nodes",
    "query": "SELECT \n  concat(long_name, ' (', node_id, ')') as __text, \n  node_id as __value \nFROM node_details \nORDER BY long_name"
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total nodes in mesh",
   "type": "stat",
   "description": "Total number of observed nodes in the mesh",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT COUNT(node_id) \nFROM node_details \nWHERE node_id <> '0';"
    }
   ]
  },
  {
   "title": "Active nodes in the last 30 minutes",
   "type": "stat",
   "description": "Nodes that sent any packet in the last 30 minutes",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) \nFROM node_details \nWHERE updated_at  >= NOW() - INTERVAL 30 MINUTE;"
    }
   ]
  },
  {
   "title": "Nodes naming status",
   "type": "stat",
   "description": "How many nodes are unknown and how many are known.\n\nThe unknown are ones that are either NULL in their long name or \"Unknown\" in their value",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(CASE WHEN long_name IS NULL OR long_name = 'Unknown' AND node_id != '0' THEN 1 END) AS \"Unnamed\",\n    COUNT(CASE WHEN long_name IS NOT NULL AND long_name != 'Unknown' AND node_id != '0' THEN 1 END) AS \"Named\"\nFROM\n    node_details\n\n"
    }
   ]
  },
  {
   "title": "Total packets sent",
   "type": "stat",
   "description": "Total packets sent in specified time range",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT COUNT(*) \nFROM mesh_packet_metrics \nWHERE source_id IN ($Nodes);\n"
    }
   ]
  },
  {
   "title": "Data sent on mesh in last hour",
   "type": "stat",
   "description": "Shows the total data sent on the mesh in bytes in the last hour. This includes all types of packets.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "meshtastic",
     "expr": "sum(sum_over_time(text_message_app_size_in_bytes{source_id=~\"$Nodes\"}[1h]))",
     "legendFormat": "__auto",
     "rawSql": "SELECT SUM(message_size_bytes)\nFROM mesh_packet_metrics \nWHERE rx_time >= UNIX_TIMESTAMP(NOW() - INTERVAL 1 HOUR) AND source_id IN ($Nodes);"
    }
   ]
  },
  { "title": "Main Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Channel Utilization (ChUtil)",
   "type": "timeseries",
   "description": "Shows the max recorded chanel utilization and the average",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "meshtastic",
     "expr": "avg(telemetry_app_channel_utilization{node_id=~\"$Nodes\"})",
     "legendFormat": "Chanel utilization (Avg)",
     "rawSql": "SELECT \n    AVG(dm.channel_utilization) OVER (PARTITION BY dm.node_id) AS \"ChUtil\",\n    dm.time\nFROM device_metrics AS dm \nJOIN node_details AS nd ON dm.node_id = nd.node_id\nWHERE dm.node_id IN ($Nodes)\n  AND dm.channel_utilization IS NOT NULL\nORDER BY dm.time;"
    }
   ]
  },
  {
   "title": "Duty Cycle (AirUtilTX)",
   "type": "timeseries",
   "description": "This panel shows the percentage of airtime used for transmissions in the last hour. Airtime in LoRa networks represents the duration a device occupies the radio frequency channel to send data. It's a critical metric for:\n\nNetwork capacity: Higher airtime usage indicates increased network load.\n\nRegulatory compliance: Many regions limit the total airtime per device.\n\nBattery life: More airtime generally means higher power consumption.\n\nThe data comes from Meshtastic packets, reflecting actual network usage. High percentages may suggest the need for optimization or capacity planning.",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "telemetry_app_air_util_tx{node_id=~\"$Nodes\"} > -100\nand\ndelta(telemetry_app_air_util_tx{node_id=~\"$Nodes\"}[1m]) != 0",
     "legendFormat": "{{long_name}}",
     "rawSql": "SELECT \n    nd.long_name,\n    dm.air_util_tx AS \"AirUtilTX\",\n    dm.time\nFROM device_metrics AS dm \nJOIN node_details AS nd ON dm.node_id = nd.node_id\nWHERE dm.node_id IN ($Nodes)\n  AND dm.air_util_tx IS NOT NULL\n  AND dm.air_util_tx > -100\nORDER BY dm.time;"
    }
   ]
  },
  {
   "title": "Top channel utilizers",
   "type": "timeseries",
   "description": "Displays the nodes that utilize most of the channel (On average with at least 1 update every hour)",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(3,\n  avg by (node_id, short_name, long_name) (\n    avg_over_time(telemetry_app_channel_utilization{node_id=~\"$Nodes\"}[$__range]) > 0\n    and\n    timestamp(telemetry_app_channel_utilization{node_id=~\"$Nodes\"}) > time() - 3600\n    and\n    changes(telemetry_app_channel_utilization{node_id=~\"$Nodes\"}[3h]) > 0\n  )\n)",
     "legendFormat": "{{short_name}}:{{long_name}}"
    }
   ]
  },
  {
   "title": "Packet types for selected time",
   "type": "piechart",
   "description": "Displays types of packets in the selected time range.\n\nFor more details see:\nhttps://buf.build/meshtastic/protobufs/docs/main:meshtastic#meshtastic.PortNum",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Packets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT \n    portnum,\n    COUNT(portnum) AS portnum_count,\n    time\nFROM mesh_packet_metrics \nWHERE time BETWEEN $__timeFrom() AND $__timeTo() AND source_id IN ($Nodes)\nGROUP BY portnum, time\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "The configured max hops for each client",
   "type": "gauge",
   "description": "How many hops are configured for each client",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  mesh_packet_hop_start{source_id=~\"$Nodes\"}\n  and\n  (delta(mesh_packet_hop_start{source_id=~\"$Nodes\"}[1m]) != 0)\n) by (source_id, source_long_name)",
     "legendFormat": "{{source_long_name}}"
    }
   ]
  },
  {
   "title": "Node Graph",
   "type": "nodeGraph",
   "description": "Graph that is built from Neighbor Info reports and shows the signal strenth for each line",
   "gridPos": { "h": 22, "w": 11, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n    cd.node_id AS id,\n    cd.long_name AS title,\n    cd.hardware_model AS \"detail__Hardware Detail\",\n    cd.role AS \"detail__Client Role\",\n    cd.short_name AS subtitle\nFROM\n    node_details cd\nLEFT JOIN (\n    SELECT node_id FROM node_neighbors\n    UNION\n    SELECT neighbor_id FROM node_neighbors\n) nn ON cd.node_id = nn.node_id\nWHERE nn.node_id IS NOT NULL;"
    },
    {
     "rawSql": "SELECT \n    CONCAT(neighbor_id, '_', node_id) AS id,\n    neighbor_id AS source,\n    node_id AS target,\n    snr AS mainstat,\n    CASE\n        WHEN snr < -13 THEN '#E74C3C'  -- Red for SNR < -13\n        WHEN snr < -7 THEN '#F4D03F'   -- Yellow for -13 ≤ SNR < -7\n        ELSE '#2ECC71'                 -- Green for SNR ≥ -7\n    END AS \"color\",\n    GREATEST(0.1, LEAST(2, 1 + ((snr + 13) / 10))) AS \"thickness\"\nFROM \n    node_neighbors"
    }
   ]
  },
  {
   "title": "General Information",
   "type": "table",
   "description": "Information stored in DB which includes \"hard to get\" information - that is needed to be gathered over time.",
   "gridPos": { "h": 22, "w": 13, "x": 11, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT node_id, long_name, short_name, role, hardware_model \nFROM node_details \nWHERE node_id <> '0'"
    }
   ]
  },
  {
   "title": "Nodes map",
   "type": "geomap",
   "description": "Displays the nodes on the map",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT * \nFROM node_details \nWHERE longitude IS NOT NULL AND longitude IS NOT NULL"
    }
   ]
  }
 ]
}