{
 "title": "Mesh Übersicht",
 "description": "Übersicht des lokalen Meshtastic Netzwerks",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "nodeID",
    "label": "Node ID",
    "query": "SELECT \n  CONCAT(long_name, \" \", \"(\", node_id, \")\") AS __text, \n  node_id as __value\nFROM node_details \nORDER BY long_name ASC;"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes im Mesh",
   "type": "stat",
   "description": "Gesamtzahl der beobachteten Nodes im Netz",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  COUNT(node_id)\nFROM\n  node_details\nWHERE\n  node_id <> '0';"
    }
   ]
  },
  {
   "title": "Aktive Nodes",
   "type": "stat",
   "description": "Nodes, die in einem bestimmten Zeitbereich Pakete gesendet haben",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  node_details\nWHERE\n  $__timeFilter(updated_at);"
    }
   ]
  },
  {
   "title": "Bekannte Nodes",
   "type": "stat",
   "description": "Wie viele Nodes sind bekannt?",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(node_id)\nFROM\n  node_details\nWHERE\n  long_name IS NOT NULL\n  AND long_name != 'Unknown'\n  AND node_id != '0';"
    }
   ]
  },
  {
   "title": "Unbekannte Nodes",
   "type": "stat",
   "description": "Wie viele Nodes sind unbekannt?\n\nDie unbekannten sind diejenigen, die entweder NULL in ihrem langen Namen oder „Unbekannt“ in ihrem Wert haben.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(node_id)\nFROM\n  node_details\nWHERE\n  long_name IS NULL\n  OR long_name = 'Unknown'\n  AND node_id != '0';"
    }
   ]
  },
  {
   "title": "Pakete gesendet",
   "type": "stat",
   "description": "Zeigt die kumulative Gesamtzahl der in einem bestimmten Zeitraum gesendeten Pakete.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT \n    time,\n    COUNT(*) OVER (ORDER BY time)\nFROM mesh_packet_metrics \nWHERE $__timeFilter(time)\n  AND message_size_bytes IS NOT NULL\n  AND source_id IN ($nodeID)\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Gesendete Daten",
   "type": "stat",
   "description": "Zeigt die kumulative Datenmenge der über das Mesh gesendeten Daten über den gewählten Zeitzaum an.\n\nDies umfasst alle Arten von Paketen.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "meshtastic",
     "legendFormat": "__auto",
     "rawSql": "SELECT \n    time,\n    SUM(SUM(message_size_bytes)) OVER (ORDER BY time)\nFROM mesh_packet_metrics \nWHERE $__timeFilter(time)\n  AND message_size_bytes IS NOT NULL\n  AND source_id IN ($nodeID)\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Kanalauslastung (Channel Utilization)",
   "type": "timeseries",
   "description": "Zeigt die maximal aufgezeichnete Kanalauslastung des gewählten Zeitraumes an.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "meshtastic",
     "expr": "avg(telemetry_app_channel_utilization{node_id=~\"$nodeID\"})",
     "legendFormat": "Chanel utilization (Avg)",
     "rawSql": "SELECT\n  channel_utilization AS \"Kanalauslastung\",\n  time as time\nFROM\n  device_metrics\nWHERE\n  channel_utilization IS NOT NULL\n  AND $__timeFilter(time)\n  AND node_id IN ($nodeID)\nGROUP BY\n  time,\n  node_id\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Arbeitszyklus (Air Utility TX)",
   "type": "timeseries",
   "description": "Dieses Feld zeigt den Prozentsatz der Sendezeit, der für Übertragungen im ausgewählten Zeitraum verwendet wurde. Die Sendezeit in LoRa-Netzwerken entspricht der Dauer, während der ein Gerät den Funkfrequenzkanal zum Senden von Daten belegt. Dies ist eine wichtige Kennzahl für:\n\nNetzwerkkapazität: Eine höhere Sendezeitnutzung deutet auf eine erhöhte Netzwerkauslastung hin.\n\nEinhaltung gesetzlicher Vorschriften: In vielen Regionen ist die Gesamt-Sendezeit pro Gerät begrenzt.\n\nBatterielebensdauer: Eine längere Sendezeit bedeutet in der Regel einen höheren Stromverbrauch.\n\nDie Daten stammen aus Meshtastic-Paketen und spiegeln die tatsächliche Netzwerknutzung wider. Hohe Prozentsätze können auf einen Optimierungsbedarf oder die Notwendigkeit einer Kapazitätsplanung hindeuten.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "telemetry_app_air_util_tx{node_id=~\"$nodeID\"} > -100\nand\ndelta(telemetry_app_air_util_tx{node_id=~\"$nodeID\"}[1m]) != 0",
     "legendFormat": "{{long_name}}",
     "rawSql": "SELECT\n  device_metrics.time,\n  AVG(device_metrics.air_util_tx) as value,\n  CONCAT(\n    COALESCE(\n      node_details.short_name,\n      SUBSTRING(device_metrics.node_id, 1, 8)\n    ),\n    ' (',\n    node_details.long_name,\n    ')'\n  ) as metric\nFROM\n  device_metrics\n  LEFT JOIN node_details ON device_metrics.node_id = node_details.node_id\nWHERE\n  device_metrics.air_util_tx IS NOT NULL\n  AND $__timeFilter(device_metrics.time)\n  AND device_metrics.node_id IN ($nodeID)\nGROUP BY\n  device_metrics.time,\n  device_metrics.node_id,\n  node_details.short_name,\n  node_details.hardware_model\nORDER BY\n  device_metrics.time;"
    }
   ]
  },
  {
   "title": "Pakettypen",
   "type": "piechart",
   "description": "Zeigt die Arten von Paketen im ausgewählten Zeitbereich an.\n\nWeitere Informationen finden Sie unter:\nhttps://buf.build/meshtastic/protobufs/docs/main:meshtastic#meshtastic.PortNum",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  portnum,\n  COUNT(*) as count\nFROM\n  mesh_packet_metrics\nWHERE\n  $__timeFilter(time)\n  AND source_id IN ($nodeID)\nGROUP BY\n  portnum\nORDER BY\n  time DESC;"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "description": "Zeigt eine aktuell Liste der Nodes sortiert nach Aktualität an.",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 12 },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  node_details.node_id AS \"Node ID\",\n  node_details.short_name AS \"Kurzname\",\n  node_details.long_name AS \"Langname\",\n  node_details.hardware_model AS \"Hardware\",\n  device_metrics.battery_level AS \"Batterie (%)\",\n  device_metrics.channel_utilization AS \"Kannalauslastung (%)\",\n  device_metrics.air_util_tx AS \"Air Utility TX (%)\",\n  node_details.updated_at AS \"Aktualisiert\"\nFROM\n  node_details\n  JOIN device_metrics ON node_details.node_id = device_metrics.node_id\n  JOIN mesh_packet_metrics ON node_details.node_id = mesh_packet_metrics.source_id\nWHERE\n  node_details.node_id <> '0'\n  AND node_details.node_id IN($nodeID)\nGROUP BY\n  node_details.node_id\nORDER BY\n  node_details.updated_at DESC;"
    }
   ]
  },
  {
   "title": "Standorte",
   "type": "geomap",
   "description": "Zeig die gefundenen Nodes auf einer Karte an.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  node_id AS \"Node ID\",\n  short_name AS \"Kurzname\",\n  long_name AS \"Langname\",\n  hardware_model AS \"Hardware\",\n  role AS \"Rolle\",\n  latitude AS \"Latitude\",\n  longitude AS \"Longitude\",\n  altitude AS \"Altitude\",\n  precision_bits AS \"Präzision\"\nFROM\n  node_details\nWHERE\n  longitude != 0\n  AND longitude != 0\n  AND node_id IN($nodeID)\nGROUP BY\n  node_id"
    }
   ]
  }
 ]
}