{
 "title": "Node Übersicht",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodeID",
    "label": "Node ID",
    "query": "SELECT \n  CONCAT(long_name, \" \", \"(\", node_id, \")\") AS __text, \n  node_id as __value\nFROM node_details \nORDER BY long_name ASC;"
   },
   {
    "name": "relatives",
    "label": "relatives",
    "query": "SELECT\n  neighbor_id AS \"source\",\n  node_id AS \"target\"\nFROM\n   node_neighbors\nWHERE\n  node_id = \"${nodeID}\"\n  OR neighbor_id = \"${nodeID}\""
   }
  ]
 },
 "panels": [
  {
   "title": "Pakete gesendet",
   "type": "stat",
   "description": "Zeigt die kumulative Gesamtzahl der in einem bestimmten Zeitraum gesendeten Pakete.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  time,\n  COUNT(*) OVER (\n    ORDER BY\n      time\n  )\nFROM\n  mesh_packet_metrics\nWHERE\n  $__timeFilter(time)\n  AND message_size_bytes IS NOT NULL\n  AND source_id IN ($nodeID)\nGROUP BY\n  time\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Pakettypen gesendet",
   "type": "table",
   "description": "Zeigt die Arten von Paketen im ausgewählten Zeitbereich an.\nFor more details see:\nhttps://buf.build/meshtastic/protobufs/docs/main:meshtastic#meshtastic.PortNum",
   "gridPos": { "h": 5, "w": 14, "x": 5, "y": 0 },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  portnum,\n  COUNT(*) as count\nFROM\n  mesh_packet_metrics\nWHERE\n  $__timeFilter(time)\n  AND source_id IN ($nodeID)\nGROUP BY\n  portnum\nORDER BY\n  time DESC;"
    }
   ]
  },
  {
   "title": "Letztes Paket gesendet",
   "type": "stat",
   "description": "Das letzte Mal, als ein Paket von diesem Knoten gesendet wurde",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "timestamp((\n  count(mesh_packet_total{source_id=\"$nodeID\"}) by (source_id)\n  -\n  count(mesh_packet_total{source_id=\"$nodeID\"} offset 1m) by (source_id)\n) > 0)",
     "legendFormat": "__auto",
     "rawSql": "SELECT\n  *\nFROM\n  mesh_packet_metrics\nWHERE\n  $__timeFilter(time)\n  AND source_id IN ($nodeID)\nORDER BY\n  time DESC;"
    }
   ]
  },
  {
   "title": "Pakete empfangen",
   "type": "stat",
   "description": "Zeigt die kumulative Gesamtzahl der in einem bestimmten Zeitraum empfangenen Pakete.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  time,\n  COUNT(*) OVER (\n    ORDER BY\n      time\n  )\nFROM\n  mesh_packet_metrics\nWHERE\n  $__timeFilter(time)\n  AND message_size_bytes IS NOT NULL\n  AND destination_id IN ($nodeID)\nGROUP BY\n  time\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Pakettypen empfangen",
   "type": "table",
   "description": "Zeigt die Arten von Paketen im ausgewählten Zeitbereich an.\nFor more details see:\nhttps://buf.build/meshtastic/protobufs/docs/main:meshtastic#meshtastic.PortNum",
   "gridPos": { "h": 5, "w": 14, "x": 5, "y": 5 },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  portnum,\n  COUNT(*) as count\nFROM\n  mesh_packet_metrics\nWHERE\n  $__timeFilter(time)\n  AND destination_id IN ($nodeID)\nGROUP BY\n  portnum\nORDER BY\n  time DESC;"
    }
   ]
  },
  {
   "title": "Letztes Paket empfangen",
   "type": "stat",
   "description": "Das letzte Mal, als ein Paket von diesem Knoten empfangen wurde.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "timestamp((\n  count(mesh_packet_total{source_id=\"$nodeID\"}) by (source_id)\n  -\n  count(mesh_packet_total{source_id=\"$nodeID\"} offset 1m) by (source_id)\n) > 0)",
     "legendFormat": "__auto",
     "rawSql": "SELECT\n  *\nFROM\n  mesh_packet_metrics\nWHERE\n  $__timeFilter(time)\n  AND destination_id IN ($nodeID)\nORDER BY\n  time DESC;"
    }
   ]
  },
  {
   "title": "Nodedetails",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM\n  node_details\nWHERE\n  node_id = '$nodeID'\nLIMIT\n  1"
    }
   ]
  },
  {
   "title": "Node Graph",
   "type": "nodeGraph",
   "description": "Grafik, die aus Nachbarschaftsinformationsberichten erstellt wurde und die Signalstärke für jede Leitung anzeigt.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  node_id AS \"id\",\n  long_name AS \"title\",\n  short_name AS \"subtitle\",\n  hardware_model AS \"Hardware\",\n  role AS \"Rolle\",\n  \"#808080\" AS color\nFROM\n  node_details\nWHERE\n  node_id = \"$nodeID\"\n  OR node_id = \"$relatives\""
    },
    {
     "rawSql": "SELECT \n    CONCAT(neighbor_id, '_', node_id) AS id,\n    neighbor_id AS \"source\",\n    node_id AS \"target\",\n    snr AS \"mainstat\",\n    CASE\n        WHEN snr < -13 THEN '#E74C3C'  -- Red for SNR < -13\n        WHEN snr < -7 THEN '#F4D03F'   -- Yellow for -13 ≤ SNR < -7\n        ELSE '#2ECC71'                 -- Green for SNR ≥ -7\n    END AS \"color\",\n    GREATEST(0.1, LEAST(2, 1 + ((snr + 13) / 10))) AS \"thickness\"\nFROM \n    node_neighbors\n    WHERE (neighbor_id IN (${nodeID:singlequote}) OR neighbor_id IN (${relatives:singlequote}))\n    AND (node_id IN (${nodeID:singlequote}) OR node_id IN (${relatives:singlequote}))"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "meshtastic",
     "expr": "topk(1, telemetry_app_temperature{node_id=\"$nodeID\"})",
     "legendFormat": "{{long_name}}",
     "rawSql": "SELECT\n  temperature,\n  time\nFROM\n  environment_metrics\nWHERE\n  node_id = $nodeID\n  AND temperature IS NOT NULL\n  AND $__timeFilter(time)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Node-Konfiguration",
   "type": "table",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  node_id,\n  \n  -- Environment Update Informationen\n  CASE\n    WHEN environment_update_interval_sec > 1\n    THEN SEC_TO_TIME(environment_update_interval_sec)\n    ELSE NULL\n  END AS environment_update_interval,\n  DATE_FORMAT(environment_update_last_timestamp, '%Y-%m-%d %H:%i:%s') AS environment_update_last_timestamp,\n  \n  -- Device Update Informationen  \n  CASE\n    WHEN device_update_interval_sec > 1\n    THEN SEC_TO_TIME(device_update_interval_sec)\n    ELSE NULL\n  END AS device_update_interval,\n  DATE_FORMAT(device_update_last_timestamp, '%Y-%m-%d %H:%i:%s') AS device_update_last_timestamp,\n  \n  -- Air Quality Update Informationen\n  CASE\n    WHEN air_quality_update_interval_sec > 1\n    THEN SEC_TO_TIME(air_quality_update_interval_sec)\n    ELSE NULL\n  END AS air_quality_update_interval,\n  DATE_FORMAT(air_quality_update_last_timestamp, '%Y-%m-%d %H:%i:%s') AS air_quality_update_last_timestamp,\n  \n  -- Power Update Informationen\n  CASE\n    WHEN power_update_interval_sec > 1\n    THEN SEC_TO_TIME(power_update_interval_sec)\n    ELSE NULL\n  END AS power_update_interval,\n  DATE_FORMAT(power_update_last_timestamp, '%Y-%m-%d %H:%i:%s') AS power_update_last_timestamp,\n  \n  -- Range Test Informationen\n  CASE\n    WHEN range_test_interval_sec > 1\n    THEN SEC_TO_TIME(range_test_interval_sec)\n    ELSE NULL\n  END AS range_test_interval,\n  DATE_FORMAT(range_test_last_packet_timestamp, '%Y-%m-%d %H:%i:%s') AS range_test_last_packet_timestamp,\n  \n  -- PAX Counter Informationen\n  CASE\n    WHEN pax_counter_interval_sec > 1\n    THEN SEC_TO_TIME(pax_counter_interval_sec)\n    ELSE NULL\n  END AS pax_counter_interval,\n  DATE_FORMAT(pax_counter_last_timestamp, '%Y-%m-%d %H:%i:%s') AS pax_counter_last_timestamp,\n  \n  -- Neighbor Info Informationen\n  CASE\n    WHEN neighbor_info_interval_sec > 1\n    THEN SEC_TO_TIME(neighbor_info_interval_sec)\n    ELSE NULL\n  END AS neighbor_info_interval,\n  DATE_FORMAT(neighbor_info_last_timestamp, '%Y-%m-%d %H:%i:%s') AS neighbor_info_last_timestamp,\n  \n  -- Map Broadcast Informationen\n  CASE\n    WHEN map_broadcast_interval_sec > 1\n    THEN SEC_TO_TIME(map_broadcast_interval_sec)\n    ELSE NULL\n  END AS map_broadcast_interval,\n  DATE_FORMAT(map_broadcast_last_timestamp, '%Y-%m-%d %H:%i:%s') AS map_broadcast_last_timestamp,\n  \n  -- MQTT Informationen\n  mqtt_encryption_enabled,\n  mqtt_json_enabled,\n  mqtt_configured_root_topic,\n  DATE_FORMAT(mqtt_info_last_timestamp, '%Y-%m-%d %H:%i:%s') AS mqtt_info_last_timestamp,\n  \n  -- Letzte Aktualisierung\n  DATE_FORMAT(last_updated, '%Y-%m-%d %H:%i:%s') AS last_updated\n  \nFROM node_configurations\nWHERE\n  (environment_update_interval_sec > 1 OR\n   device_update_interval_sec > 1 OR\n   air_quality_update_interval_sec > 1 OR\n   power_update_interval_sec > 1 OR\n   range_test_interval_sec > 1 OR\n   pax_counter_interval_sec > 1 OR\n   neighbor_info_interval_sec > 1 OR\n   map_broadcast_interval_sec > 1)\n  AND node_id = $nodeID\nLIMIT 50;"
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "meshtastic",
     "expr": "topk(1, telemetry_app_relative_humidity{node_id=\"$nodeID\"})",
     "legendFormat": "{{long_name}}",
     "rawSql": "SELECT\n  relative_humidity,\n  time\nFROM\n  environment_metrics\nWHERE\n  node_id = $nodeID\n  AND relative_humidity IS NOT NULL\n  AND $__timeFilter(time)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Standort",
   "type": "geomap",
   "description": "Zeig den gefundenen Node auf einer Karte an.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  node_id AS \"Node ID\",\n  short_name AS \"Kurzname\",\n  long_name AS \"Langname\",\n  hardware_model AS \"Hardware\",\n  role AS \"Rolle\",\n  latitude AS \"Latitude\",\n  longitude AS \"Longitude\",\n  altitude AS \"Altitude\",\n  precision_bits AS \"Präzision\"\nFROM\n  node_details\nWHERE\n  longitude != 0\n  AND longitude != 0\n  AND node_id IN($nodeID)\nGROUP BY\n  node_id"
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "dataset": "meshtastic",
     "expr": "topk(1, telemetry_app_barometric_pressure{node_id=\"$nodeID\"})",
     "legendFormat": "{{long_name}}",
     "rawSql": "SELECT\n  barometric_pressure,\n  time\nFROM\n  environment_metrics\nWHERE\n  node_id = $nodeID\n  AND barometric_pressure IS NOT NULL\n  AND $__timeFilter(time)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "meshtastic",
     "expr": "telemetry_app_battery_level{node_id=\"$nodeID\"}",
     "legendFormat": "{{long_name}} | Model: {{hardware_model}} | Role: {{role}}",
     "rawSql": "SELECT\n  device_time AS time,\n  battery_level\nFROM\n  node_telemetry\nWHERE\n  $__timeFilter(device_time)\n  AND battery_level IS NOT NULL\n  AND node_id IN ($nodeID)\nGROUP BY\n  device_time\nORDER BY\n  device_time;"
    }
   ]
  },
  {
   "title": "Spannung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "meshtastic",
     "expr": "telemetry_app_voltage{node_id=\"$nodeID\"}",
     "legendFormat": "{{long_name}} | Model: {{hardware_model}} | Role: {{role}}",
     "rawSql": "SELECT\n  device_time AS time,\n  voltage\nFROM\n  node_telemetry\nWHERE\n  $__timeFilter(device_time)\n  AND voltage IS NOT NULL\n  AND node_id IN ($nodeID)\nGROUP BY\n  device_time\nORDER BY\n  device_time;"
    }
   ]
  },
  {
   "title": "Strommessung",
   "type": "timeseries",
   "description": "Zeigt den gemessenen Strom aus den Kanälen (1, 2, 3) an.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "telemetry_app_ch1_current{node_id=\"$nodeID\"}",
     "legendFormat": "Channel 1",
     "rawSql": "SELECT\n  time,\n  ch1_current,\n  ch2_current,\n  ch3_current\nFROM\n  power_metrics\nWHERE\n  $__timeFilter(time)\n  AND (\n    ch1_current IS NOT NULL\n    OR ch2_current IS NOT NULL\n    OR ch3_current IS NOT NULL\n  )\n  AND node_id IN ($nodeID)\nGROUP BY\n  time\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Spannungsmessung",
   "type": "timeseries",
   "description": "Zeigt die gemessenen Spannung aus den Kanälen (1, 2, 3) an.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  time,\n  ch1_voltage,\n  ch2_voltage,\n  ch3_voltage\nFROM\n  power_metrics\nWHERE\n  $__timeFilter(time)\n  AND (\n    ch1_voltage IS NOT NULL\n    OR ch2_voltage IS NOT NULL\n    OR ch3_voltage IS NOT NULL\n  )\n  AND node_id IN ($nodeID)\nGROUP BY\n  time\nORDER BY\n  time;"
    }
   ]
  }
 ]
}