{
 "title": "PAX Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nodeID",
    "label": "Node ID",
    "query": "SELECT \n  CONCAT(long_name, \" \", \"(\", node_id, \")\") AS __text, \n  node_id as __value\nFROM node_details \nORDER BY long_name ASC;"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Standorte",
   "type": "geomap",
   "description": "Zeigt Knoten auf der Karte und die Anzahl der Geräte um diesen Knoten herum an.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  node_id AS \"Node ID\",\n  short_name AS \"Kurzname\",\n  long_name AS \"Langname\",\n  hardware_model AS \"Hardware\",\n  role AS \"Rolle\",\n  latitude AS \"Latitude\",\n  longitude AS \"Longitude\",\n  altitude AS \"Altitude\",\n  precision_bits AS \"Präzision\"\nFROM\n  node_details\nWHERE\n  longitude != 0\n  AND longitude != 0\n  AND node_id IN($nodeID)\nGROUP BY\n  node_id"
    },
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  ble_beacons,\n  time\nFROM\n  pax_counter_metrics\nWHERE\n  node_id IN($nodeID);\n"
    },
    {
     "dataset": "meshtastic",
     "rawSql": "SELECT\n  wifi_stations,\n  time\nFROM\n  pax_counter_metrics\nWHERE\n  node_id IN($nodeID);\n"
    }
   ]
  },
  {
   "title": "PAX Uptime",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "meshtastic",
     "expr": "pax_uptime{node_id=~\"$Nodes\"}",
     "legendFormat": "{{long_name}}",
     "rawSql": "SELECT\n  node_id,\n  \n  -- PAX Counter Informationen\n  CASE\n    WHEN pax_counter_interval_sec > 1\n    THEN SEC_TO_TIME(pax_counter_interval_sec)\n    ELSE NULL\n  END AS pax_counter_interval,\n  DATE_FORMAT(pax_counter_last_timestamp, '%Y-%m-%d %H:%i:%s') AS pax_counter_last_timestamp,\n  \nFROM node_configurations\nWHERE\n  pax_counter_interval_sec > 1\n  AND node_id IN($nodeID)"
    }
   ]
  },
  {
   "title": "Verteilung der Geräte",
   "type": "histogram",
   "description": "Verteilung der Anzahl der Geräte über die Zeit",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Histogrammdaten der Pax-Zähler",
   "type": "heatmap",
   "description": "Histogramm für Knoten und die Anzahl der von ihnen erfassten Geräte",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 12 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "PAX counters",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pax_ble{node_id=~\"$Nodes\"}",
     "legendFormat": "{{short_name}}-{{node_id}}-Bluetooth",
     "rawSql": "SELECT\n  ble_beacons,\n  time\nFROM\n  pax_counter_metrics\nWHERE\n  node_id IN($nodeID);\n"
    },
    {
     "dataset": "meshtastic",
     "expr": "pax_wifi{node_id=~\"$Nodes\"}",
     "legendFormat": "{{short_name}}-{{node_id}}-Wifi",
     "rawSql": "SELECT\n  wifi_stations,\n  time\nFROM\n  pax_counter_metrics\nWHERE\n  node_id IN($nodeID);\n"
    }
   ]
  }
 ]
}